apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui
  namespace: microshop
  labels:
    app: microshop
    component: ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microshop
      component: ui
  template:
    metadata:
      labels:
        app: microshop
        component: ui
    spec:
      containers:
      - name: ui
        image: quay.io/microshop/ui:latest
        ports:
        - containerPort: 3000
        env:
        - name: STORE_URL
          value: "https://store.dh4r4pvj.ga"
        - name: CHECKOUT_URL
          value: "https://checkout.dh4r4pvj.ga"
---
apiVersion: v1
kind: Service
metadata:
  name: ui
  namespace: microshop
  labels:
    app: microshop
    component: ui
spec:
  ports:
    - port: 80
      targetPort: 3000
  selector:
    app: microshop
    component: ui
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ui
  namespace: microshop
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  rules:
    - host: www.dh4r4pvj.ga
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ui
                port:
                  number: 80
  tls:
  - hosts:
    - www.dh4r4pvj.ga
    secretName: ui-cert
